"""Validate the public catalog and emit a synchronous module for offline WebView.

Edit data/rok-army.json, then run this script. --check detects a stale bundle.
No network access or external dependencies are used.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'app/src/main/assets/game'
STATS = ('mobility', 'firepower', 'armor', 'reconnaissance', 'logistics')


def validate(data):
    assert data['schema_version'] == 1
    geography = json.loads((ASSETS / 'geography.js').read_text(encoding='utf-8').split(' = ', 1)[1].rstrip(';\n'))
    assert data['map']['columns'] == geography['columns'] and data['map']['rows'] == geography['rows']
    assert data['map']['precision'] == 'city_county_game_region'
    units = {u['id']: u for u in data['units']}
    assert len(units) == len(data['units']), 'duplicate formation ID'
    for region in data['regions'].values():
        assert set(region['hex']) == {'q', 'r'}
        assert type(region['hex']['q']) is int and 0 <= region['hex']['q'] < data['map']['columns']
        assert type(region['hex']['r']) is int and 0 <= region['hex']['r'] < data['map']['rows']
    for u in units.values():
        assert u['service'] == '육군'
        assert u['unit_level'] in ('본부', '사령부', '군단', '사단', '여단')
        assert u['region'] == data['regions'][u['region_id']]['name']
        profile = data['stat_profiles'][u['stat_profile']]
        assert u['game_type'] == profile['game_type'] and u['unit_type'] == profile['unit_type']
        assert u['deployable'] == (u['game_type'] is not None)
        for key in STATS:
            assert type(u[key]) is int and 0 <= u[key] <= 100 and u[key] == profile[key]
        assert u['source'] and u['source_date'] == data['checked_at']
        covered = set()
        for ref in u['source']:
            assert ref['source_id'] in data['sources'] and ref['fields']
            covered.update(ref['fields'])
        assert 'unit_name' in covered
        if u['region_basis'] == 'public_municipality':
            assert 'region' in covered
        else:
            assert u['region_basis'] == 'parent_region_game_fallback' and u['parent_unit']
            assert u['region_id'] == units[u['parent_unit']]['region_id']
        if u['major_equipment']:
            assert u['equipment_scope'] == 'public_unit_report' and 'major_equipment' in covered
        if u['parent_unit']:
            assert 'parent_unit' in covered
        seen = {u['id']}
        parent = u['parent_unit']
        while parent:
            assert parent in units and parent not in seen, 'invalid parent or hierarchy cycle'
            seen.add(parent)
            parent = units[parent]['parent_unit']
    # These fields are deliberately outside this game's public data contract.
    forbidden = {'latitude', 'longitude', 'lat', 'lon', 'lng', 'coordinates', 'address',
                 'base_location', 'patrol_pattern', 'movement_route', 'vulnerability'}
    def inspect(value):
        if isinstance(value, dict):
            assert not forbidden.intersection(value), 'precise/operational field is unsupported'
            for child in value.values():
                inspect(child)
        elif isinstance(value, list):
            for child in value:
                inspect(child)
    inspect(data)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = json.loads((ASSETS / 'data/rok-army.json').read_text(encoding='utf-8'))
    validate(data)
    content = '// Generated by tools/build-army-data.py; edit data/rok-army.json.\n'
    content += 'export const ARMY_DATA_RAW = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n'
    target = ASSETS / 'army-data.js'
    if args.check:
        assert target.read_text(encoding='utf-8') == content, 'army-data.js is stale; run tools/build-army-data.py'
    else:
        target.write_text(content, encoding='utf-8', newline='\n')
    print(f"Army catalog validated: {len(data['units'])} records, {sum(u['deployable'] for u in data['units'])} playable")


if __name__ == '__main__':
    main()
