"""Compile vendored Korea sources offline. PNG is never input."""
import argparse
import csv
import hashlib
import itertools
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'app/src/main/assets/game'
DATA = ASSETS / 'data/korea-map'

def read_csv(name):
    with (DATA / name).open(encoding='utf-8', newline='') as f:
        return list(csv.DictReader(f))

def regression(pairs):
    xs, ys = zip(*pairs)
    x, y = sum(xs)/len(xs), sum(ys)/len(ys)
    slope = sum((a-x)*(b-y) for a,b in pairs)/sum((a-x)**2 for a in xs)
    return [slope, y-slope*x]

def contains(x, y, ring):
    inside = False
    px, py = ring[-1]
    for cx, cy in ring:
        if (cy > y) != (py > y) and x < (px-cx)*(y-cy)/(py-cy)+cx:
            inside = not inside
        px, py = cx, cy
    return inside

def compile_map():
    mask = (DATA / 'korea_72x126_mask.txt').read_text(encoding='utf-8').splitlines()
    rows, cols = len(mask), len(mask[0])
    assert (cols, rows) == (72, 126)
    assert all(len(row) == cols and set(row) <= {'.','#'} for row in mask)
    places = read_csv('korea_72x126_cities_ports_adjacent_sea.csv')
    stations = read_csv('korea_72x126_ktx_stations.csv')
    paths = read_csv('korea_72x126_ktx_hex_paths.csv')
    # Geographic fit is only for ownership and municipality anchors. Sites use exact CSV cells.
    refs = [p for p in places if p['snapped'] == 'False' and p['name_en'] != 'Dokdo']
    lon_fit = regression([(float(p['lon']), int(p['raw_col']) + .5*(int(p['raw_row'])%2)) for p in refs])
    lat_fit = regression([(float(p['lat']), int(p['raw_row'])) for p in refs])
    countries = json.loads((DATA/'control-boundaries.json').read_text(encoding='utf-8'))['countries']
    polygons = [(1 if c['id']=='410' else 2,p) for c in countries for p in c['polygons']]
    def owner(row,col):
        if mask[row][col] == '.': return 0
        lon = (col + .5*(row%2)-lon_fit[1])/lon_fit[0]
        lat = (row-lat_fit[1])/lat_fit[0]
        for side,poly in polygons:
            if contains(lon,lat,poly[0]) and not any(contains(lon,lat,hole) for hole in poly[1:]): return side
        # Generalized mask coast/islands can sit outside vector outlines: nearest Korean boundary.
        return min((min((x-lon)**2*.62+(y-lat)**2 for x,y in poly[0]),side) for side,poly in polygons)[1]
    owners = [owner(r,c) for r in range(rows) for c in range(cols)]
    rle = []
    for key, group in itertools.groupby(owners): rle.extend([key,len(list(group))])
    def tile(row,col,rail=False):
        r,c=int(row),int(col)
        assert 0<=r<rows and 0<=c<cols and (mask[r][c]=='#' or rail), (r,c,'site/path is not land')
        return r*cols+c
    sites = []
    north={'Pyongyang','Wonsan','Hamhung','Chongjin','Sinuiju','Nampo','Kaesong'}
    for p in places:
        r,c=(p['port_row'],p['port_col']) if p['type']=='port' else (p['row'],p['col'])
        tid=tile(r,c)
        assert owners[tid] == (2 if p['name_en'] in north else 1), p['name_en']
        sites.append(dict(id='place-'+p['name_en'].lower(), name=p['name_ko'], kind=p['type'], tile=tid,sourceHexId=p['port_hex_id'] if p['type']=='port' else p['hex_id']))
    for i,s in enumerate(stations): sites.append(dict(id=f'station-{i}',name=s['station']+'역',kind='rail',tile=tile(s['row'],s['col'],True),sourceHexId=s['hex_id']))
    routes=[]
    for route_id, group in itertools.groupby(paths,key=lambda p:p['route_id']):
        points=list(group)
        assert [int(p['sequence']) for p in points] == list(range(len(points)))
        routes.append(dict(route_id=route_id,kind=points[0]['kind'],label=points[0]['label'],points=[dict(sequence=int(p['sequence']),tile=tile(p['row'],p['col'],True),sourceHexId=p['hex_id']) for p in points]))
    files = ['korea_72x126_mask.txt','korea_72x126_cities_ports_adjacent_sea.csv','korea_72x126_ktx_hex_paths.csv','korea_72x126_ktx_stations.csv']
    return dict(id='korea-72x126-v1',columns=cols,rows=rows,layout='odd-r',hexRadius=10,source='kingarthurhkm-oss/korea-map',sourceHashes={f:hashlib.sha256((DATA/f).read_bytes()).hexdigest() for f in files},georeference=dict(lon=lon_fit,lat=lat_fit,basis='least-squares fit to original city CSV raw offsets; sites use exact CSV tiles'),ownersRLE=rle,sites=sites,railRoutes=routes,camera=dict(padding=.9,minZoom=.12,maxZoom=6),labels=[dict(text='대한민국',col=41,row=84,color='#a9ccd0'),dict(text='북한',col=35,row=36,color='#c6a1a3'),dict(text='동 해',col=59,row=60,color='#698b9e'),dict(text='서 해',col=10,row=82,color='#698b9e')])

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    geography=compile_map()
    content='// Generated by tools/build-korea-map.py from authoritative text/CSV sources.\nexport const GEOGRAPHY = '+json.dumps(geography,ensure_ascii=False,separators=(',',':'))+';\n'
    target=ASSETS/'geography.js'
    if args.check: assert target.read_text(encoding='utf-8')==content, 'geography.js stale; run tools/build-korea-map.py'
    else: target.write_text(content,encoding='utf-8',newline='\n')
    print(f"Korea map validated: {geography['columns']*geography['rows']} tiles, {len(geography['sites'])} sites, {len(geography['railRoutes'])} routes")

if __name__=='__main__': main()
